[package]
name = "conetracing"
version = "0.1.0"
authors = ["Kevin Watters <kevinwatters@gmail.com>"]

[dependencies]
unrust = { path = "../unrust" }
unrust-derive = { path = "../unrust/unrust-derive" }
num = "*"
